export class Resource {
  public iD: number;
  public firstName: string;
  public fatherName: string;
  public email: string;
  public designationID = 0;
  public departmentID = 0;
  public dreatedOn: string;
  public updatedOn: string;
  public isActive: any;
  public isActiveNew: boolean;
  public login: string;
  public isMailRequired: number;
  public reportingPersonID = 0;
  public locationID = 0;
  public isManager: string;
  public isManagerNew: boolean;
  public dateOfJoining: string;
  public gender= 'Male';
  public maritalStatus = 'Unmarried';
  public employeeID: string;
  public isProbation: string;
  public isProbationNew: boolean;
  public dateOfBirth: string;
  public anniversary: string;
  public contactNo: string;
  public managerID = 0;
  public qualification: string;
  public totalWorkExperience: number;
  public permanentAddress: string;
  public presentAddress: string;
  public alternativeEmail = '';
  public bankAccountNo: string;
  public alternativeContactNo= '';
  public hrId = 0;
  public extensionNo: number;
  public extensionNoSTD: number;
  public imageName = '';
  public dateOfSeparation: string;
  public currentSalary: string;
  public rManager: string;
  public manager: string;
  public hRManager: string;
  public designationName: string;
  public departmentName: string;
  public location: string;
  public projectManager: string;
  public uniqueId: string;
  public hRName: string;
  public reportingPerson: string;
  public bankName: string;
  public panCard: string;
  public esiNo: string;
  public uanNo: string;
  public pfNo: string;
  public aadharCard: string;
  public salaryDetailId: number;
  public totalPaybleSalary: string;
  public basicSalary: string;
  public hra: string;
  public lta: string;
  public medical: string;
  public specialAllowence: string;
  public tDSDeducton: string;
  public pFAmount: number;
  public gratuity: number;
}
